# Generated by Django 6.0 on 2025-12-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='day',
            field=models.CharField(blank=True, choices=[('mon', 'Понеділок'), ('tue', 'Вівторок'), ('wed', 'Середа'), ('thu', 'Четвер'), ('fri', "П'ятниця"), ('sat', 'Субота'), ('sun', 'Неділя')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
