# Generated by Django 4.0.8 on 2025-12-04 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0002_task_day_task_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='day',
            field=models.CharField(choices=[('mon', 'Понеділок'), ('tue', 'Вівторок'), ('wed', 'Середа'), ('thu', 'Четвер'), ('fri', 'П’ятниця'), ('sat', 'Субота'), ('sun', 'Неділя')], default='mon', max_length=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='task',
            name='time',
            field=models.TimeField(default='12:00'),
            preserve_default=False,
        ),
    ]
